baseURL: "https://www.labooner.com/"
languageCode: "en-gb"
title: "labooner blog"

permalinks:
  blog: "/:filename/"

menu:
  main:
    - name: Home
      pre: home
      url: "/"
      weight: 1
    - name: Blog
      pre: edit
      url: "/blog/"
      weight: 2
    - name: Tags
      pre: tag
      url: "/tags/"
      weight: 3

taxonomies:
  tag: "tags"

params:
  dateFormat: Jan 2, 2006
  homeText: "Hello world! This in my blog"